<a href="https://colab.research.google.com/github/salacamifda/distance-and-time-starter-code/blob/main/Distance_and_time_Starter_Code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Starter Code

# Exploring NumPy Arrays: Distance and Time

1) Import the numpy library

In [2]:
import numpy as np

2) Create a numpy array called "distance" that includes the following distances (in meters): 100, 200, 400, 800, 1500, 3000, 5000, 10000

In [18]:
distance = np.array([100, 200, 400, 800, 1500, 3000, 5000, 10000])

In [4]:
print(distance)

[100, 200, 400, 800, 1500, 3000, 5000, 10000]


3) Use the np.min() and np.max() functions to find the minimum and maximum distances

In [8]:
maxDistance = max(distance)
minDistance = min(distance)

print(maxDistance)
print(minDistance)


10000
100


4) To find the average distance, use the np.mean() function

In [9]:
averageDistance = np.average(distance)

print(averageDistance)

2625.0


5) use the np.sum() function to find the total distance

In [10]:
totalDistance = sum(distance)

print(totalDistance)

21000


6) Another valuable function is the np.cumsum() function which outputs the cumulative sum...notice the output will be 100, 300, 700 as it adds each new distance

In [12]:
cumsumDistance = np.cumsum(distance)

print(cumsumDistance)

[  100   300   700  1500  3000  6000 11000 21000]


7) To round all of the values in an array, use np.round()

In [15]:
roundDistance = np.round(cumsumDistance)

print(roundDistance)

arr=np.array([1.57279, 2.0843,  2.795,3.1465])
arr1 = np.round(arr)

print(arr1)

[  100   300   700  1500  3000  6000 11000 21000]
[2. 2. 3. 3.]


8) Create a numpy array called time that includes the following times (in seconds):  10.62, 21.34, 48.25, 113.43, 233.96, 506.53, 866.17, 1757.45

In [17]:
time = np.array([10.62, 21.34, 48.25, 113.43, 233.96, 506.53, 866.17, 1757.45])

print(time)

[  10.62   21.34   48.25  113.43  233.96  506.53  866.17 1757.45]


9) the values in your time array correspond to olympic records for running the corresponding distances.  Perform the calculation needed to find the speed (in m/s) for each record distance.  Note that speed is distance divided by time.

In [23]:
speed = distance/time

print(distance)
print(time)
print(speed)
print(np.round(speed))

[  100   200   400   800  1500  3000  5000 10000]
[  10.62   21.34   48.25  113.43  233.96  506.53  866.17 1757.45]
[9.41619586 9.37207123 8.29015544 7.0528079  6.41135237 5.92265019
 5.77253888 5.69006231]
[9. 9. 8. 7. 6. 6. 6. 6.]


10) One common problem data scientists run into is that we are given information in units that are not consistent.  
For example, we might want to compare data that is given in meters to second to data that is given in miles per hour. A cheetah is the fastest land animal which can reach speeds of 75.0 miles per hour.  
In order to compare our olympians to a cheetah, we need to be able to convert from one unit to another.
Perform calculations to convert the olympic record speeds from meters/second into miles per hour.  Note: 1 meter = 0.00062 miles

How do our olympians compare to the cheetah?

(Hint: Speed in m/s multiplied by 0.00062 and multiplied by 3600 will give speed in miles per hour)

In [42]:
distanceMiles = distance* 0.00062
print("Distance in meters")
print(distance)
print("Distance in miles")
print(distanceMiles)


print("------------------------------------------")
timeHours = time/3600
print("Time in seconds")
print(time)
print("Time in hours")
print(timeHours)
print("------------------------------------------")


print("--------------Speed in Meters per second----------------------------")
print(speed)
print("--------------Speed in Miles per Hour----------------------------")
speedMH = distanceMiles/timeHours
print(speedMH)
print("------------------------------------------")


Distance in meters
[  100   200   400   800  1500  3000  5000 10000]
Distance in miles
[0.062 0.124 0.248 0.496 0.93  1.86  3.1   6.2  ]
------------------------------------------
Time in seconds
[  10.62   21.34   48.25  113.43  233.96  506.53  866.17 1757.45]
Time in hours
[0.00295    0.00592778 0.01340278 0.03150833 0.06498889 0.14070278
 0.24060278 0.48818056]
------------------------------------------
--------------Speed in Meters per second----------------------------
[9.41619586 9.37207123 8.29015544 7.0528079  6.41135237 5.92265019
 5.77253888 5.69006231]
--------------Speed in Miles per Hour----------------------------
[21.01694915 20.91846298 18.50362694 15.74186723 14.31013849 13.21935522
 12.88430678 12.70021907]
------------------------------------------


Chettah is around 59 miles/hours faster than our Olympians

In [44]:
speedAverage = np.average(speedMH)
print(speedAverage)
print("------------------------------------------")

cheetahSpeed = 75
speedDifference = cheetahSpeed - speedAverage 
print(np.round(speedDifference))

16.161865731998713
------------------------------------------
59.0
